## Demo construct script

Import('env')

demoenv = env.Clone()

if 'g++' in demoenv['TOOLS'] :
    pass
elif 'msvc' in demoenv['TOOLS'] :
    demoenv.AppendUnique( CCFLAGS = [ '/Fdobj\\vc80.pdb' ] )

## Grab all the cpp files
sources = Glob('*.cpp')
object_list  = demoenv.Object(source = sources)
demoenv.Program(target = '#/bin/demo', source = object_list, LIBPATH = '#/lib', LIBS = ['cug', 'shp'] )
