## Demo construct script

Import('env')

## Only build the file when the timestamp has changed, and the MD5 hash is different
Decider('MD5-timestamp')

## Grab all the cpp files
sources = Glob('*.cpp')

env.Append( CPPPATH = ['.'] )
env.Append( CCFLAGS = ['-g', '-Wall', '-funroll-loops', '-O3', '-ffast-math'] )
env.Append( CPPDEFINES = ['_DEBUG'] )
env.Append( LIBS = ['cug'] )
env.Append( LIBPATH = ['../lib'] )

object_list  = env.Object(source = sources)
env.Program(target = '../bin/cug-demo', source = object_list)
