## Lib construct script

Import('env')

## Tell scons about the build directory
BuildDir('obj/', 'src/')
## Only build the file when the timestamp has changed, and the MD5 hash is different
Decider('MD5-timestamp')

## Grab all the cpp files
sources = Glob('*.cpp')

env.Append( CPPPATH = ['../include'] )
env.Append( CCFLAGS = ['-g', '-Wall', '-funroll-loops', '-O3', '-ffast-math'] )
env.Append( CPPDEFINES = ['_DEBUG'] )

object_list  = env.Object(source = sources)
t = env.StaticLibrary(target = '../lib/cug', source = object_list)

Default(t)
